spring:
  profiles:
    active: dev
server:
  port: 8080
api:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://personal-gym-api.onrender.com
springdoc:
  swagger-ui:
    path: /fitness-consultant-documentation
  api-docs:
    path: /fitness-consultant-apidocs
  packages-to-scan: br.com.fitnessconsultant.controller