spring:
  application:
    name: Personal GYM api
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_gym_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-message: always
api:
  jwt:
    secret: ${JWT_SECRET}
    jwtExpirationSeg: 10800
